In [16]:
import numpy as np

array = np.ones((5, 5))

# array[1:4, 1:4] = 0
# array[2, 2] = 9

# array[0:5, 0] = 0
# array[0:5, 4] = 0
# array[0, 0:5] = 0
# array[4, 0:5] = 0
print(array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
